AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for lambda-python3.8

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
      Cors:
          AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
          AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
          AllowOrigin: "'*'"
  Function:
    Timeout: 30

Resources:
  PinkoapidevProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Application:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /product
            Method: post

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./application
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/"
  HelloWorldFunction:
    Description: "Retrieve products for pinko"
    Value: !GetAtt PinkoapidevProductFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Pinko product function"
    Value: !GetAtt PinkoapidevProductFunction.Arn
